### ISSUE TITLE
page anchor headings obscured by fixed header in some cases

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/CITZ-IMB-playbook#15]
In some cases, page headings are obscured when they are navigated to using the left sidebar. For example, watch when I click in the menu to go to **Step 1** here:

![anchor obscured](https://user-images.githubusercontent.com/16946297/87701908-7fdfbd00-c74d-11ea-9dfc-a432c502f690.gif)

Will try to find a solution and submit a PR for this. Great work on this resource so far!

**Comment by marchkellyj** [comment]
Hey Mark,

Thanks so much for this feedback! We were unable to replicate this on our side. Can you please supply us with some additional information so we can try to replicate it and troubleshoot?

What kind of computer are you using (Operating System)?
What kind of browser are you using?
Do you have any browser extensions installed?

Thanks,
Kelly

**Comment by mark-a-wilson** [comment]
This was in **Safari** on **OS X Catalina 10.15.5**. 

Thanks for suggesting that as, now that I test on Chrome, I do not get the same issue. So this is probably not worth your effort to investigate. 

It appears connected to the left-nav which jumps around quite a bit in Safari when you're scrolling a lot.

**Comment by CITZ-rwk** [comment]
this issue is being closed as we developed for Edge and Chrome.
