### ISSUE TITLE
How to reuse this Jekyll theme without cloning the entire project

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/CITZ-IMB-playbook#21]
Hello @marchkellyj, @Harpalus, @CITZ-rwk, @poornima-sivanand:

@CraigShutko emailed me asking how he might reuse the theme you've created here without cloning all of the content as well. His questions:

> I looked here: https://bcgov.github.io/CITZ-IMB-playbook/theme/
But that just seems to describe the look feel and to iterate that it’s a clone of the 18F Us Web Design System, but doesn’t detail how others can reuse the theme. If not – any advice on how to make use of the theme simply? Or advice on the best way to use the theme? I suppose I can always clone the repo and rename, just wondering if there is a better way that I don’t understand.

Can you provide advice? 

Is there a way we could clone, refine, and provide this theme as a standalone, gov-themed template for people to create new GitHub Pages sites?

**Comment by CITZ-rwk** [comment]
sorry, left as an exercise to the reader
